services:
  homepage:
    build:
      context: .
    container_name: Homepage
    restart: always
    ports:
      - "{{ ports.homepage }}:80"  # Map port 80 in the container to homepage port on the host
