# Template the HTML file with configuration variables
- name: Template main.html with configuration
  become: true
  ansible.builtin.template:
    src: /home/{{ ansible_env.USER }}/NAS_drive/ansible/tasks/index_page_compose/main.html.j2
    dest: /home/{{ ansible_env.USER }}/NAS_drive/ansible/tasks/index_page_compose/main.html
    owner: "{{ ansible_env.USER }}"
    group: "{{ ansible_env.USER }}"
    mode: '0644'

# Run index_page docker compose
- name: Create and start index page
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_env.USER }}/NAS_drive/ansible/tasks/index_page_compose
  register: output