# Create directories required by Vaultwarden
- name: Create directory for vaultwarden storage
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0777'
  loop:
    - /media/{{ mount_point }}/Documents/vw-data


- name: Template the docker-compose file
  template:
    src: vaultwarden_compose/docker-compose.yml.j2
    dest: /home/{{ ansible_env.USER }}/NAS_drive/ansible/tasks/vaultwarden_compose/docker-compose.yml


- name: Create and start vaultwarden
  become: true
  community.docker.docker_compose_v2:
    project_src: /home/{{ ansible_env.USER }}/NAS_drive/ansible/tasks/vaultwarden_compose
  register: output